[package]
name = "zombodb"
description = "Making Postgres and Elasticsearch work together like it's 2021"
version = "3000.0.3"
edition = "2018"
build = "build.rs"
readme = "README.md"
license = "LICENSE.md"

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
default = [ "pg12" ]
pg10 = [ "pgx/pg10", "pgx-tests/pg10" ]
pg11 = [ "pgx/pg11", "pgx-tests/pg11" ]
pg12 = [ "pgx/pg12", "pgx-tests/pg12" ]
pg13 = [ "pgx/pg13", "pgx-tests/pg13" ]
pg_test = [ ]

[dependencies]
byteorder = "1.4.3"
chrono = "0.4.19"
crossbeam-channel = "0.5.1"
dashmap = "4.0.2"
indexmap = "1.7.0"
lalrpop-util = "0.19.6"
lazy_static = "1.4.0"
levenshtein = "1.0.5"
memoffset = "0.6.4"
num_cpus = "1.13.0"
pathfinding = "2.2.1"
pgx = { git = "https://github.com/zombodb/pgx", rev = "fa8ece3232df3fb75562a376d04a060488a17176" }
pgx-macros = { git = "https://github.com/zombodb/pgx", rev = "fa8ece3232df3fb75562a376d04a060488a17176" }
rayon = "1.5.1"
regex = "1.5.4"
serde = { version = "1.0.130", features = [ "derive" ] }
serde_json = { version = "1.0.66", features = [ "preserve_order" ] }
serde_cbor = "0.11.1"
sqlformat = "0.1.6"
ureq = { version = "2.1.1", features = [ "json" ] }
url = "2.2.2"

[build-dependencies]
lalrpop = { version = "0.19.6", features = [ "lexer" ] }
built = { version = "0.5.1", features = [ "git2", "semver" ] }

[dev-dependencies]
pgx-tests = { git = "https://github.com/zombodb/pgx", rev = "fa8ece3232df3fb75562a376d04a060488a17176" }
libc = "0.2.99"

[profile.dev]
panic = "unwind"
debug = true
opt-level = 0

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1

